### ISSUE TITLE
Information messages

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/smartcampus.api.manager#6]
Some messages behaviour not help user understanding.

Some scenario 1. [valid for policy/resource/app]
1. I edit with success a policy and correctly I see the success message.
2. I remain on the same page and I edit another policy field correctly.
So in this scenario there's nothing in page that show me that operation is ended and how, because success message is present since previous operation

Scenario 2.
1. I edit a field of policy with a wrong value, correctly system show me a error message.
2. I remain on the same page and a insert a correct value in field, system show me a success message on the top the previous one.
3. If I remain on the same page an I edit correctly or not another policy field, system seems do nothing because messages are present since previous operations.

A possible solution is to show messages with a duration

**Comment by gcanobbio** [comment]
When I successfully update an element, a message is shown. After 7 seconds it is deleted.
If I update again, a message is shown but it is no longer deleted.

**Comment by gcanobbio** [comment]
I used $timeout but it is instantiated only once.
What I need is to create an instance of interval and then remember to delete it.
